### ISSUE TITLE
自动生成字段注释时，第一个字段的注释位置不对

### ISSUE THREAD

**Issue by sunshine98** [mars-men/GsonFormatPlus#16]
fljb的字段注释嵌套进去了。
public class test {

    /**
     * 注释字段
     */ /**
     * FLJB : 1
     * SPFL02 : 兰蔻
     * MJBJ : 0
     * SPF_SPFL01 : null
     * SPFL01 : lk
     */

    @JsonProperty("FLJB")
    private Integer fljb;

**Comment by junziqiao** [comment]
谢谢，我已经修复了，过几天发版

**Comment by mars-men** [comment]
junziqiao 在1.5.9版本已支持，正在提交审核。
