### ISSUE TITLE
希望支持默认开启Json Format的配置

### ISSUE THREAD

**Issue by sunshine98** [mars-men/GsonFormatPlus#17]
首先这个插件太好用了，整合了很多新技术。
但是我每次把json数据复制到编辑框后都要手动点一下Format,可否实现复制Json后自动格式化？
给开发人员点赞，提高效率必备工具！

**Comment by junziqiao** [comment]
谢谢你提出的问题，我尽快优化一下

**Comment by junziqiao** [comment]
将在1.5.9版本修复

**Comment by mars-men** [comment]
junziqiao 在1.5.9版本已支持，正在提交审核。
