### ISSUE TITLE
字段带有*/时解析出现问题

### ISSUE THREAD

**Issue by TruthKeeper** [mars-men/GsonFormatPlus#19]
Version：1.5.8

JSON：
{
    "skuId": 50378,
    "baseUnitSpecification": "¥**/斤",
}
当字段带有 */ 时部分字段会解析为注解修饰， 删除baseUnitSpecification字段后skuId解析正常

![image](https://user-images.githubusercontent.com/16833189/112781611-c710a280-907d-11eb-9e79-c30d3785b371.png)
![image](https://user-images.githubusercontent.com/16833189/112781655-d8f24580-907d-11eb-881a-a6247eb98607.png)

**Comment by junziqiao** [comment]
你把字符串的斜杠去掉

**Comment by junziqiao** [comment]
![image](https://user-images.githubusercontent.com/41858086/112832526-0663e100-90c8-11eb-843c-c1e1581a64ad.png)
json后面不应该有逗号，请把斜杠也去掉
