### ISSUE TITLE
支持json5特别是里面的注释

### ISSUE THREAD

**Issue by jiangcaida** [mars-men/GsonFormatPlus#7]
能不能由
![image](https://user-images.githubusercontent.com/52436053/101607262-58acc380-3a3f-11eb-853d-f7dd8bc272a1.png)
变成
![R4B@ZW54MHK{%N5I HPY8Z9](https://user-images.githubusercontent.com/52436053/101607494-a3c6d680-3a3f-11eb-8f6a-33288be03ba8.png)

**Comment by mars-men** [comment]
有支持json5

**Comment by jiangcaida** [comment]
首先，感谢您的回复。可能我的问题描述不清楚，重接描述如下：
不支持注释映射到实体属性的注释，如



注释丢失，而且这个例子还出bug了，丢失了4个字段







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mars-men/GsonFormatPlus"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月9日(星期三) 下午5:40
收件人:&nbsp;"mars-men/GsonFormatPlus"<GsonFormatPlus@noreply.github.com&gt;;
抄送:&nbsp;"蒋才达"<425661280@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [mars-men/GsonFormatPlus] 支持json5特别是里面的注释 (#7)





 
有支持json5

**Comment by mars-men** [comment]
![screen](https://user-images.githubusercontent.com/1943377/101614565-1471f100-3a48-11eb-891b-e7da00766423.gif)

**Comment by jiangcaida** [comment]
非常感谢！！！
必须点击右上角“Format”按钮才能使json里面的注释生效（操作文档里没说明）



此外，提个建议，注释为空不生成注释内容为属性名的注释是否更好一点，因为有些字段意思比较明确不必写注释（但加一个注释内容为属性名的注释有点别扭）







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mars-men/GsonFormatPlus"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月9日(星期三) 下午5:59
收件人:&nbsp;"mars-men/GsonFormatPlus"<GsonFormatPlus@noreply.github.com&gt;;
抄送:&nbsp;"蒋才达"<425661280@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [mars-men/GsonFormatPlus] 支持json5特别是里面的注释 (#7)
